site_name: "de.NBI Cloud Wiki"
docs_dir: /srv_root/docs/wiki
site_dir: /var/www/html/wiki
theme:
  name: material
  palette:
    primary: 'light blue'
    accent: 'light blue'
  logo: 'img/denbi.svg'
  favicon: 'img/denbi.svg'
repo_name: 'deNBI/cloud-user-docs'
repo_url: 'https://github.com/deNBI/cloud-user-docs'
edit_uri: blob/master/wiki/
plugins:
 - search
 - mkpdfs
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - matomo.js

nav:
  - 'Home' : index.md
  - 'Registration' : registration.md
  - 'Citation and publication': citation_and_publication.md
  - 'Portal' :
    - 'Allocation': portal/allocation.md
    - 'Resource/Lifetime Modifications': portal/modification.md
    - 'Project Overview': portal/project_overview.md
    - 'Profile Page': portal/user_information.md
    - 'Using Vault': portal/vault_user.md
  - 'Simple VM':
      - 'New instance': simple_vm/new_instance.md
      - 'Instance overview': simple_vm/instance_overview.md
      - 'Instance details': simple_vm/instance_detail.md
      - 'New cluster': simple_vm/new_cluster.md
      - 'Cluster overview': simple_vm/cluster_overview.md
      - 'Volumes': simple_vm/volumes.md
      - 'Images/Snapshots': simple_vm/snapshots.md
      - 'Customization': simple_vm/customization.md
  - 'OpenStack Quickstart' : quickstart.md
  - 'Security' : security.md
  - 'Concept' :
    - 'OpenStack Basics' : Concept/basics.md
    - 'OpenStack Components' : Concept/openstack.md
    - 'Flavors' : Concept/flavors.md
    - 'Images' : Concept/images.md
  - 'Tutorials' :
    - 'Access de.NBI Virtual Machines from Windows 10' : Tutorials/Win10_SSH/index.md
    - 'Access a SimpleVM with Mosh' : Tutorials/Mosh/index.md
    - 'SimpleVM File Transfer' : Tutorials/File_Transfer_Methods/index.md
    - 'Ansible Automation' : Tutorials/Ansible/index.md
    - 'Bibigrid' : Tutorials/BiBiGrid/index.md
    - 'Blast on BiBiGrid' : Tutorials/BlastOnBiBiGrid/index.md
    - 'Install latest CUDA version' : Tutorials/CUDA/index.md
    - 'Object Storage' : Tutorials/ObjectStorage/index.md
    - 'Save FloatingIPs' : Tutorials/SaveFloatingIPs/index.md
    - 'Set up RStudio' : Tutorials/RStudio_Server/index.md
    - 'Theia Web IDE': Tutorials/TheiaIde/index.md
    - 'UserData' : Tutorials/UserData/index.md
  - 'FAQ' : 'FAQ.md'
  - 'Compute Center Specific' :
    - 'Giessen' : Compute_Center/Giessen.md
    - 'Bielefeld' : Compute_Center/Bielefeld.md
    - 'Heidelberg Uni' : Compute_Center/Heidelberg.md
    - 'Heidelberg DKFZ' : Compute_Center/Heidelberg-DKFZ.md
    - 'Tuebingen' : Compute_Center/Tuebingen.md
    - 'Freiburg' : Compute_Center/Freiburg.md
    - 'Berlin' : Compute_Center/Berlin.md
  - 'Cloud Admin':
    - 'Jenkins + Haproxy with JuJu': cloud_admin/juju_jenkins.md
    - 'Configure OpenStack to use Elixir AAI via OpenID Connect': cloud_admin/elixir_OIDC.md
    - 'Register your identity provider for ELIXIR': cloud_admin/identity_provider.md
    - 'News management': cloud_admin/news_management.md
    - 'Vault management': cloud_admin/vault_admin.md
